### ISSUE TITLE
DeadDialog Test Failed

### ISSUE THREAD

**Issue by kokoichi206** [kokoichi206/rhythm_game#53]
**Is your feature request related to a problem? Please describe.**
isDeadDialogUnCancelable Test Failed during this actions
https://github.com/kokoichi206/rhythm_game/actions/runs/1182919563

**Describe the solution you'd like**
reference
https://android.tecc0.com/?p=65

**Comment by kokoichi206** [comment]
```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@c337b88 is not valid; is your activity running?
at android.view.ViewRootImpl.setView(ViewRootImpl.java:907)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
at android.app.Dialog.show(Dialog.java:342)
at io.kokoichi.sample.rhythmgame.GameView.lambda$showDialog$2$GameView(GameView.java:560)
at io.kokoichi.sample.rhythmgame.GameView$$ExternalSyntheticLambda2.run(Unknown Source:4)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by kokoichi206** [comment]
at pressHome() function in testPauseButton()
```
androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 1605, 75 and precision: 16, 16' on view 'is a root view.'.
```
